### ISSUE TITLE
Any working example?

### ISSUE THREAD

**Issue by anup-a** [jpalumickas/node-oauth2-server-model-prisma#4]
Hey @jpalumickas ,

I'm looking to setup github oauth 2.0 on my react/express/prisma app, but didn't find any appropriate resources. Could you give any working example for this package?

**Comment by jpalumickas** [comment]
Hey @anup-a,

Which grant flow you want to use with GitHub authentication?

**Comment by anup-a** [comment]
As it is side project I'm working on I'm flexible with oauth grant types, but "refresh tokens" is what I prefer.
